### ISSUE TITLE
Ruby Gem?

### ISSUE THREAD

**Issue by jheth** [webmerge/api-ruby#1]
I'd like to re-use the work you've done but this isn't a ruby gem. Do you have any plans to package it as one?

**Comment by webmerge** [comment]
Hey Joe,

To be honest, a customer of our wrote this Ruby code.  We do not have 
anyone on staff that is knowledgeable in Ruby.  Would it be something 
that you could write an contribute back to the Github project?

Jeremy Clarke

WebMerge
http://www.webmerge.me





------ Original Message ------

**Comment by jheth** [comment]
Yeah, absolutely.  Thanks for asking.

**Comment by webmerge** [comment]
That's great - we really appreciate it!

Jeremy Clarke

WebMerge
http://www.webmerge.me





------ Original Message ------

**Comment by jheth** [comment]
Jeremy,

See what you think of that. If you're good with it I'll push this version to rubygems.org and it'll be available for everyone.

**Comment by webmerge** [comment]
Thanks @jheth !!

**Comment by jheth** [comment]
Here's the pushed version  https://rubygems.org/gems/web_merge
