### ISSUE TITLE
Unable to perform live merge

### ISSUE THREAD

**Issue by arnoldmarunda** [webmerge/api-ruby#14]
The code below is performing a Test Merge, 
`api.merge_document(doc_id=XXXXXX, key="xxxxxx", fields)`

How to I command a live merge?

I have also tried `api.merge_document(doc_id=XXXXXX, key="xxxxxx", fields, {test: 0})` with no success.

Please advise. 

Many Thanks

**Comment by plicjo** [comment]
Hey Arnold,

I never had to explicitly specify test mode as false in my application.

I have the following working in my app:

```
client = WebMerge::API.new(key: ENV['WEB_MERGE_API_KEY'], secret: ENV['WEB_MERGE_API_SECRET'])
client.merge_document(document_id, document_key, fields, download: 1)
```

**Comment by arnoldmarunda** [comment]
@plicjo 

Thanks for your response, I did not proceed to use the gem. However, I'm sure your response will be of use to someone else
